!SESSION 2018-01-20 14:09:42.224 -----------------------------------------------
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

This is a continuation of log file D:\Files\WorkSpaceRisorseweb\git\Drive-In\.metadata\.bak_0.log
Created Time: 2018-01-20 14:09:53.504
!SESSION 2018-01-20 14:09:42.224 -----------------------------------------------
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_151
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=it_IT
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.egit.ui 2 0 2018-01-20 14:09:53.504
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\gdm20'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.oomph.setup.ui 2 0 2018-01-20 14:09:53.688
!MESSAGE java.lang.NullPointerException
!STACK 0
java.lang.NullPointerException
	at org.eclipse.oomph.setup.ui.SetupUIPlugin.performStartup(SetupUIPlugin.java:352)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin.access$3(SetupUIPlugin.java:346)
	at org.eclipse.oomph.setup.ui.SetupUIPlugin$1$1.run(SetupUIPlugin.java:243)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.core 4 0 2018-01-20 14:23:41.870
!MESSAGE An exception occurred during push on URI https://github.com/gdm1995/Drive-In: Nothing to push.
!STACK 0
org.eclipse.jgit.errors.TransportException: Nothing to push.
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1197)
	at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:197)
	at org.eclipse.egit.ui.internal.push.PushWizard$PushJob.run(PushWizard.java:297)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 4 0 2018-01-20 14:23:41.910
!MESSAGE Can't connect to any repository: https://github.com/gdm1995/Drive-In (Nothing to push.)

!ENTRY org.eclipse.egit.ui 4 0 2018-01-20 14:25:47.221
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:224)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:212)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:197)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:208)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Impossibile accedere al file. Un altro processo ha bloccato una parte del file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:303)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2018-01-20 14:27:58.857
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:224)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:212)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:197)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:208)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Impossibile accedere al file. Un altro processo ha bloccato una parte del file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:303)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2018-01-20 14:29:50.076
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:224)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:212)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:197)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:208)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Impossibile accedere al file. Un altro processo ha bloccato una parte del file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:303)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2018-01-20 14:30:44.063
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:224)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:212)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:197)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:208)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Impossibile accedere al file. Un altro processo ha bloccato una parte del file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:303)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.core 4 0 2018-01-20 14:33:17.465
!MESSAGE An exception occurred during push on URI https://github.com/gdm1995/Drive-In: https://github.com/gdm1995/Drive-In: not authorized
!STACK 0
org.eclipse.jgit.errors.TransportException: https://github.com/gdm1995/Drive-In: not authorized
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:498)
	at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:387)
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:154)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1200)
	at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:197)
	at org.eclipse.egit.ui.internal.push.PushOperationUI.execute(PushOperationUI.java:167)
	at org.eclipse.egit.ui.internal.push.PushOperationUI$1.run(PushOperationUI.java:229)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.egit.ui 4 0 2018-01-20 14:34:35.848
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:224)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:212)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:197)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:208)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Impossibile accedere al file. Un altro processo ha bloccato una parte del file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:303)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more

!ENTRY org.eclipse.egit.ui 4 0 2018-01-20 14:34:59.256
!MESSAGE Exception caught during execution of add command
!STACK 0
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:211)
	at org.eclipse.egit.core.op.CommitOperation.addUntracked(CommitOperation.java:224)
	at org.eclipse.egit.core.op.CommitOperation.access$4(CommitOperation.java:212)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:197)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:208)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:98)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.IOException: Impossibile accedere al file. Un altro processo ha bloccato una parte del file
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(Unknown Source)
	at org.eclipse.jgit.util.IO.readFully(IO.java:303)
	at org.eclipse.jgit.internal.storage.file.ObjectDirectoryInserter.insert(ObjectDirectoryInserter.java:103)
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:187)
	... 7 more
